redis/lettuce

src/main/java/com/lambdaworks/redis/pubsub/PubSubCommandHandler.java

Read buffer bytes need to be discarded by decode().
See issue #21 for more information.

Fix issue #21 - memory leak

---

src/main/java/com/lambdaworks/redis/pubsub/RedisPubSubConnectionImpl.java

The scenario requires two or more close-by disconnections
1. Connect to Redis
2. Subscribe successfully to a channel
3. Forcibly kill the connection (by taking down Redis for example)
4. Let lettuce reconnect successfully
5. Forcibly kill the connection again right before activate() successfully subscribes
6. Let lettuce reconnect successfully
7. RedisPubSubConnectionImpl.channels is empty and the channel will stay unsubscribed
There doesn't seem to be a reason to clear out channels and patterns.
It is only used for persistence over different connections.
There is no downside to having a channel in that set even if the subscription was not successful.

Fix channel loss on reconnect

---

src/main/java/com/lambdaworks/redis/RedisClient.java
src/test/java/com/lambdaworks/redis/TimeTest.java

It was backwards. 10 seconds was resulting in 0 instead of 10,000

Fix time conversion for timeout settings.

---

src/main/java/com/lambdaworks/redis/PooledConnectionInvocationHandler.java
src/test/java/com/lambdaworks/redis/PoolConnectionTest.java

The borrowed object would be returned to the pool on pool.freeResource() properly
If close() was called, it would return the resource to the pool,
then null the connection.

Pool return no longer nulls connection

---

pom.xml

Java8 will fail when building due to stricter javadoc requirements. This will disable that linting. Errors look like this:
```
[ERROR] src/main/java/com/lambdaworks/redis/BaseRedisAsyncConnection.java:47: warning: no description for @param
```
Alternative is to always use `-Dmaven.javadoc.skip=true` on the command line
Slightly modified from pom.xml at
https://github.com/dropwizard/metrics
and
https://jdpgrailsdev.github.io/blog/2014/04/03/maven_java8_javadoc.html
for the none

Update pom to suppress javadoc errors on Java8

---

pom.xml

Small one: I build the shaded jar and ran into ClassNotFound for com.google.common.primitives.Chars when loading SlotHash
It was being excluded in the shaded jar.

Removing exclusion for Guavas primitives in shading, used by SlotHash

---

src/main/java/com/lambdaworks/redis/BaseRedisAsyncConnection.java
src/main/java/com/lambdaworks/redis/BaseRedisConnection.java
src/main/java/com/lambdaworks/redis/RedisAsyncConnection.java
src/main/java/com/lambdaworks/redis/RedisAsyncConnectionImpl.java
src/main/java/com/lambdaworks/redis/RedisClusterConnection.java
src/main/java/com/lambdaworks/redis/RedisCommandBuilder.java
src/main/java/com/lambdaworks/redis/RedisConnection.java
src/main/java/com/lambdaworks/redis/protocol/CommandType.java
src/test/java/com/lambdaworks/redis/SyncAsyncApiConvergenceTest.java

This is to surface some redis cluster commands on the normal non-cluster connection interface..
We need to connect via a non-cluster client to perform read operations on the slave. The readonly() command allows the slave to answer if it contains the slot for the key. The other additions are cluster query commands that can help a client determine more information about the node it's connected to.
I just added the commands directly to the BaseRedis*Connection interfaces. An alternative could be to create a new RedisClusterQueryConnection interface that has just the readonly command and query cluster* commands
Added readonly command to allow a non-cluster aware slave connection perform read
operations.
Add clusterNodes command to BaseConnection. If the node is a cluster, allows simple
client …

Add some cluster commands to non-cluster client: Readonly, and expose cluster query commands

---

src/main/java/com/lambdaworks/redis/codec/Utf8StringCodec.java

This was what I was attempting to test when I found issue #42. There is a potential threading issue in the decoder.
It was syncing on chars, which can be reassigned in the called method.
Instead just synchronizing on the Codec itself. Left reformatting till later.

Fix synchronized issue

---

src/main/java/com/lambdaworks/redis/RedisAsyncConnectionImpl.java
src/test/java/com/lambdaworks/redis/UnixDomainSocketTest.java

Remove synchronization on dispatch methods in order to prevent deadlocks. CommandHandler holds a reentrant lock which allows to get a lock within the same thread on reconnecting. Clients issuing a command during connection activation will wait until the connection is activated.

Remove synchronized keywords #57

---

RELEASE-NOTES.md
src/assembly/bin.xml

By changing the file extension the rendering of the document on GitHub looks much better.

Docs: Change RELEASE-NOTES file extension to md for Markdown

---

src/main/java/com/lambdaworks/redis/RedisURI.java
src/test/java/com/lambdaworks/redis/RedisURITest.java

* RedisURI.java, RedisURITest.java - add timeout configuration to Redis connection string

Added configurable timeout to connection string

---

src/main/java/com/lambdaworks/redis/protocol/CommandArgs.java

At the moment Lettuce uses a private helper method accepting a long parameter to write the length of a String or byte array to redis.
First off, this length will be always "int",
secondly, the method uses a hand written StringBuilder and number % 10 algorithm to translate the long into a string.
It will produce a String 4321 for a length of 1234. This string will be reversed and the char values appended to the buffer.
The JDK however comes with the handy util Integer.toString(intValue) which will produce a correctly ordered String. This method is much faster and also benefits from improvements done to the JDK
(this was actually done quite recently: http://mail.openjdk.java.net/pipermail/core-libs-dev/2015-November/036765.html)
In summary this improves CPU and memory usage of this method.

Use much faster JDK utility for converting an int to a byte sequence.

---

README.md

~Updates the Maven Central badge in the README to the new artifact coordinates.~
Removes the Maven Central badge in the README since the 4.x artifact is superseded by the 5.x artifact, which is maintained in a different branch.

Remove Maven Central badge

---

src/test/java/io/lettuce/core/RedisURIBuilderUnitTests.java

Add @DisabledOnOs(OS.WINDOWS) to two tests - `redisSocket` and
`redisSocketWithPassword` that fail in Windows:
```
java.lang.IllegalArgumentException: Illegal character in authority at index 15: redis-socket://C:\Users\konstantinsh\IdeaProjects\lettuce-core\work\socket-6479
at java.base/java.net.URI.create(URI.java:883)
at io.lettuce.core.RedisURI.create(RedisURI.java:233)
```
Tests are disabled on Windows as socket connections are not supposed
to be used on OS other that Unix.

Disable RedisURIBuilderUnitTests failing on Windows OS

---

README.md

Update code for pub/sub to listen on the stateful connection object.

---

pom.xml

[Netty 4.1.47.Final released](https://netty.io/news/2020/03/09/4-1-47-Final.html)

upgrade netty to 4.1.47.Final

---

pom.xml

Fixed the build issue on aarch64. Previously build of lettuce-core was failing on aarch64 with below error: 
`[ERROR] Failed to execute goal on project lettuce-core: Could not resolve dependencies for project io.lettuce:lettuce-core:jar:6.0.0.BUILD-SNAPSHOT: Failure to find io.netty:netty-tcnative:jar:linux-aarch_64:2.0.31.Final in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]`
- Update netty-tcnative to 2.0.33.Final which includes aarch64 jar
- Add profile to set classifier for aarch64 in pom.xml

Add support for aarch64

---

src/main/java/io/lettuce/core/output/NestedMultiOutput.java
src/test/java/io/lettuce/core/output/NestedMultiOutputUnitTests.java

Implement set(double) in NestedMultiOutput

---

src/main/java/io/lettuce/core/resource/DefaultClientResources.java

(Sorry to hear about your phone @mp911de, hope you managed to sort it out somehow.)
Discovered while using this class, seems like a pretty straight-forward thing to fix to me so here goes. Thanks for a great Redis client. :pray:

DefaultClientResources: fix typos

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/RedisCommandBuilder.java
src/main/java/io/lettuce/core/api/async/RedisStreamAsyncCommands.java
src/main/java/io/lettuce/core/api/reactive/RedisStreamReactiveCommands.java
src/main/java/io/lettuce/core/api/sync/RedisStreamCommands.java
src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionStreamAsyncCommands.java
src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionStreamCommands.java
src/main/kotlin/io/lettuce/core/api/coroutines/RedisStreamCoroutinesCommands.kt
src/main/kotlin/io/lettuce/core/api/coroutines/RedisStreamCoroutinesCommandsImpl.kt
src/main/templates/io/lettuce/core/api/RedisStreamCommands.java
src/test/java/io/lettuce/core/commands/StreamCommandIntegrationTests.java

closes [https://github.com/lettuce-io/lettuce-core/issues/1505](https://github.com/lettuce-io/lettuce-core/issues/1505)

Support option CREATECONSUMER in XGROUP command

---

src/main/resources/META-INF/native-image/io.lettuce/lettuce-core/reflect-config.json

Support RedisSentineCommands in GraalVM native image

Add RedisSentinelCommands to reflect-config.json #1562

---

src/main/java/io/lettuce/core/resource/AddressResolverGroupProvider.java

Fixes: #1546 
https://github.com/yueki1993/lettuce-test-PR1517

Fix build break when missing netty-dns-resolver

---

src/test/java/io/lettuce/core/ScoredValueUnitTests.java

fixes [https://github.com/lettuce-io/lettuce-core/issues/1647](https://github.com/lettuce-io/lettuce-core/issues/1647)

Fix ScoredValueUnitTests

---

README.md
pom.xml

Fix travis links due to its domain name migration

---

src/main/java/io/lettuce/core/SocketOptions.java
src/test/java/io/lettuce/core/KeepAliveOptionsUnitTests.java

see
https://github.com/lettuce-io/lettuce-core/issues/1437#issuecomment-800940439

Change KeepAlive Default Interval to 75

---

src/main/java/io/lettuce/core/RedisURI.java

See https://github.com/lettuce-io/lettuce-core/discussions/1695#discussioncomment-547207 for context.

RedisURI: improve deprecation notice in withPassword()

---

src/main/java/io/lettuce/core/protocol/CommandHandler.java

resolve https://github.com/lettuce-io/lettuce-core/discussions/1701
just added a non-empty judgment

fix infinate print null point exception for trace bug #1701

---

src/main/java/io/lettuce/core/cluster/MultiNodeExecution.java
src/main/java/io/lettuce/core/cluster/PipelinedRedisFuture.java
src/main/java/io/lettuce/core/cluster/RedisClusterClient.java
src/main/java/io/lettuce/core/cluster/StatefulRedisClusterConnectionImpl.java
src/test/java/biz/paluch/redis/extensibility/MyExtendedRedisClusterClient.java
src/test/java/biz/paluch/redis/extensibility/MyExtendedRedisClusterClientTest.java
src/test/java/biz/paluch/redis/extensibility/MyRedisClusterConnection.java

Introduced API to allow for extending RedisClusterClient and its connections

---

src/main/java/io/lettuce/core/metrics/MicrometerOptions.java

Update MicrometerOptions.java
Fixed obvious typo in MicrometerOptions.Builder.minLatency(Duration) method.

Fixed obvious typo in MicrometerOptions.Builder.minLatency(Duration)

---

src/main/java/io/lettuce/core/resource/DefaultClientResources.java

Specify concrete scheduler name

---

pom.xml

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105

 Update log4j to 2.17 to address CVE-2021-45105.

---

src/main/java/io/lettuce/core/AbstractRedisClient.java

Makes AbstractRedisClient implement AutoClosable so that it can be used in [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) statement

Implements autoclosable interface in abstractredisclient

---

src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java

While investigating this issue (https://github.com/lettuce-io/lettuce-core/issues/2045), I discovered a minor performance issue.
Current `RedisClusterNode.forEachSlot` calls `BitSet.length` every time it loops.
The overhead here seems to be big. Please see the framegraph as follows.
We can reduce the overhead by calling `BitSet.length` only once.
When measured with JMH, you can see that the throughput(of `RedisClusterNode.forEachSlot`) is improved.
```
Benchmark                                            Mode  Cnt       Score      Error  Units
RedisClusterNodeBenchmark.originalRedisClusterNode  thrpt   25   62364.605 ± 1167.717  ops/s <-- Before
RedisClusterNodeBenchmark.updatedRedisClusterNode   thrpt   25  100597.253 ±  705.268  ops/s <-- After
```

Reduces overhead of RedisClusterNode.forEachSlot

---

src/main/java/io/lettuce/core/cluster/models/partitions/Partitions.java

To solve #2178, this PR moves invalidateCache() in the if clause below. Currently, we encounter `PartitionSelectorException` when cluster topology is refreshing.

Avoid `PartitionSelectorException` during refresh

---

src/main/java/io/lettuce/core/ConcurrentLruCache.java
src/main/java/io/lettuce/core/SocketOptions.java
src/main/java/io/lettuce/core/metrics/MetricCollector.java
src/main/java/io/lettuce/core/protocol/CommandWrapper.java

Trivial documentation fix for repeated word "the the"

Fix duplicate word occurences

---

src/test/java/io/lettuce/core/commands/SetCommandIntegrationTests.java

Before this pr, `sscanMultiple` will fail at `assertThat(cursor.getCursor()).isNotNull().isNotEqualTo("0");`, because the bottom layer is the ListPack([set_max_listpack_entries](https://github.com/redis/redis/blob/unstable/src/config.c#L3176) default is 128) structure at this time. It does not support the count option. It will return all values and set the CURSOR to 0.
see https://redis.io/commands/scan/  *Why SCAN may return all the items of an aggregate data type in a single call?* for more info.
This PR also runs successfully on versions prior to 7.0 without incompatibility.

Fix Set unit test sscanMultiple fail in redis7

---

src/main/java/io/lettuce/core/tracing/RedisObservation.java

This is trivial fix.
The observation name needs to be discussed.
---

Polish RedisObservation name & javadoc

---

src/main/java/io/lettuce/core/SetArgs.java

Update SetArgs.java builder method param comment

---

src/test/java/io/lettuce/core/pubsub/PubSubCommandBuilderUnitTests.java
src/test/java/io/lettuce/core/pubsub/RedisPubSubAsyncCommandsImplUnitTests.java
src/test/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImplUnitTests.java

Closes #2805 
- [x ] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [x ] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [x ] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) and have them applied to your changes. Don’t submit any formatting related changes.
- [x ] You submit test cases (unit or integration tests) that back your changes.

Added unit tests for most of the pubsub classes that did not have any

---

.github/workflows/snapshot.yaml
.github/workflows/version-and-release.yaml
pom.xml

Add new workflows to upload snapshots and release artifacts automatically.

Add snapshot and release workflows

---

src/main/java/io/lettuce/core/RedisHandshake.java
src/test/java/io/lettuce/core/RedisHandshakeUnitTests.java

Closes #2817 
This solution aims to bring consistency between the Lettuce driver and most other drivers maintained by the Redis team.
The current approach is - instead of probing for the version of the remote server and deciding based on that wether or not to send the CLIENT SETINFO command - to always send it and ignore the server response. There are two main reasons behind this: different flavors of the Redis server handle this in different versions and also the information sent is not critical to the operation of the driver, so failures should not necessary terminate the connection.
1. Tested against Redis 6.0 - verified no connection failures are shown
2. Tested against Redis  (unstable) - verified no connection failures are shown; and that CLIENT LIST contains the expected data on …

Send the CLIENT SETINFO command in a fire-and-forget way

---

Makefile
pom.xml
src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
src/test/java/io/lettuce/core/SslIntegrationTests.java
src/test/java/io/lettuce/core/cluster/pubsub/RedisClusterPubSubConnectionIntegrationTests.java
src/test/java/io/lettuce/core/support/PubSubTestListener.java

Addressing several stability issues with the pipeline:
1. Failing Integration tests would not fail the pipeline checks - this resulted in several tests constantly failing, and the number was rising. To address this I've added the `failsafe` plugin to the `verify` step, as suggested by the Maven best manual
2. Removed the `-B` option in the `Makefile` to improve readability in the logs
3. Modified the `io.lettuce.core.SslIntegrationTests.pubSubSsl` to attempt to verify the re-subscription process for a longer period of time, as it seems on the runners it takes more than 10 seconds (more than 60 seconds really)
4. Modified the `io.lettuce.core.cluster.pubsub.RedisClusterPubSubConnectionIntegrationTests.subscribeToShardChannelViaOtherEndpoint` to instead test replica scenario, see discussion …

Attempt to stabilize integration tests

---

src/main/java/io/lettuce/core/XReadArgs.java
src/test/java/io/lettuce/core/SocketOptionsIntegrationTests.java
src/test/java/io/lettuce/core/commands/StreamCommandIntegrationTests.java

Closes #2861 
Added a convenience utility method to read the last message from a stream

XREAD support for reading last message from stream

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/api/async/RedisScriptingAsyncCommands.java
src/main/java/io/lettuce/core/api/reactive/RedisScriptingReactiveCommands.java
src/main/java/io/lettuce/core/api/sync/RedisScriptingCommands.java
src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionScriptingAsyncCommands.java
src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionScriptingCommands.java
src/main/kotlin/io/lettuce/core/api/coroutines/RedisScriptingCoroutinesCommands.kt
src/main/kotlin/io/lettuce/core/api/coroutines/RedisScriptingCoroutinesCommandsImpl.kt
src/main/templates/io/lettuce/core/api/RedisScriptingCommands.java
src/test/java/io/lettuce/core/commands/ScriptingCommandIntegrationTests.java

-----
I am assuming the only reason why this method is missing is just an oversight, please let me know if there is anything else I should have considered.
-----
Related to #1987

Add a `evalReadOnly` overload that accepts the script as a `String`

---

.github/wordlist.txt
RELEASE-NOTES.md

Updated release notes (as part of #2880)

Updated release notes

---

.github/workflows/version-and-release.yaml

Updated release acton (as part of #2880)
* Modify the release action to call the proper maven target for release
* Make releasing manually available too

Updated release acton (as part of #2880) #2885

---

.github/PULL_REQUEST_TEMPLATE.md
src/test/java/io/lettuce/core/commands/HashCommandIntegrationTests.java

Server addressed the issues of empty list returned for missing keys

---

src/main/java/io/lettuce/core/codec/ByteArrayCodec.java
src/test/java/io/lettuce/core/codec/ByteArrayCodecUnitTests.java

Handle NPE

---

src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java
src/test/java/io/lettuce/core/cluster/models/partitions/RedisClusterNodeUnitTests.java

**Issue: #2341** 
This PR supersedes the previously closed PR #2798

[#2341] Initialize slots with empty BitSet in RedisClusterNode's constructors

---

src/main/java/io/lettuce/core/cluster/ClusterCommand.java

Update completeExceptionally on ClusterCommand using super

---

src/main/java/io/lettuce/core/protocol/SharedLock.java
src/test/java/io/lettuce/core/protocol/SharedLockTest.java

Resolves: #2905 #2879
Both of issues point to this stack trace. I have reproduced this with the sample in #2905.
After some investigation, I figured why, because the thread that holds the shared lock also requires exclusive lock in the same time.(I think it happened on error handling, or the channel was disactive when writer was writing).
```log
at io.lettuce.core.protocol.Sharedlock.lockWritersExclusive(SharedLock.java:139)
at io.lettuce.core.protocol.SharedLock.doexclusive(SharedLock.java:114)
at io.lettuce.core.protocol.DefaultEndpoint.doExclusive(DefaultEndpoint.java:741)
```

fix:deadlock when reentrant exclusive lock #2905 #2879

---

src/main/java/io/lettuce/core/ClientOptions.java
src/test/java/io/lettuce/core/ClientOptionsIntegrationTests.java
src/test/java/io/lettuce/core/cluster/RedisClusterSetupTest.java
src/test/java/io/lettuce/core/protocol/ConnectionFailureIntegrationTests.java
src/test/java/io/lettuce/core/reliability/AtLeastOnceTest.java
src/test/java/io/lettuce/core/reliability/AtMostOnceTest.java

Default ClientOptions.timeoutOptions to TimeoutOptions.enabled()

---

src/main/java/io/lettuce/core/internal/Futures.java
src/test/java/io/lettuce/core/internal/FuturesUnitTests.java

Closes #2935
I've added defensive copy for the method so that external modification could not affect stages during iteration.
As for test, I can't come up with any better idea so just used two Threads each calling allOf() and modifying stages simultaneously.
Thank you.

Add defensive copy for Futures allOf() method

---

mkdocs.yml

This adds the lettuce GitHub repo link/information to the top right corner of the docs, handy for getting back to the repo from any documentation page.

Add the github repo url to the doc config

---

src/main/java/io/lettuce/core/protocol/CommandHandler.java
src/test/java/io/lettuce/core/tracing/SynchronousIntegrationTests.java

Propagate database number, user, and RedisURI into Tracing

---

src/main/java/io/lettuce/core/ReadFrom.java
src/test/java/io/lettuce/core/cluster/ReadFromUnitTests.java

Closes #3013
Before this commit, it was not possible to use ReadFrom.valueOf for subnet and regex types. This commit introduces support for these types, as well as the use of names in underscore format

Add support for creating regex and subnet-based ReadFrom instances from a single string

---

src/main/java/io/lettuce/core/cluster/models/partitions/RedisClusterNode.java
src/test/java/io/lettuce/core/cluster/models/partitions/RedisClusterNodeUnitTests.java

Closes #3014 
Pull Request: Add hasNoSlots() Method to RedisClusterNode
This pull request addresses feature request [#3014](https://github.com/redis/lettuce/issues/3014) and is related to the bug report [#2769](https://github.com/redis/lettuce/issues/2769).
Currently, checking if a RedisClusterNode has no assigned slots involves accessing the private slots field or using getSlots(), which generates unnecessary objects and adds overhead.
This PR introduces a new method, hasNoSlots(), in the RedisClusterNode class. This method encapsulates the logic for checking if the slots field is either null or empty, improving performance and code readability.
•	Added the method public boolean hasNoSlots() to the RedisClusterNode class.
•	Added unit tests to validate the behavior of …

Add hasNoSlots() method to RedisClusterNode

---

src/main/java/io/lettuce/core/ScanIterator.java

Closes #3002
Applied the same solution as the one in the spring tracker.
Currently the infrastructure does not allow us to add a test for this, as we are using Java 8 on the pipeline.
(verified locally - of course - with Java 17 and Java 21)
Will add another issue to consider enabling the infra to at least run the tests with newer versions of Java.

ScanIterator.scan.stream().toList() causes "java.lang.IllegalStateException: Accept exceeded fixed size of 0" on Java 16+ (#3002)

---

docs/advanced-usage.md
src/main/java/io/lettuce/core/resource/DefaultClientResources.java

this PR is mostly a follow up of the missing document update of #1498

document update regarding addressResolverGroup settings

---

src/main/java/io/lettuce/core/RedisCommandBuilder.java
src/main/java/io/lettuce/core/dynamic/output/OutputRegistry.java
src/main/java/io/lettuce/core/output/StringMatchResultOutput.java
src/test/java/io/lettuce/core/commands/StringCommandIntegrationTests.java
src/test/java/io/lettuce/core/output/StringMatchResultOutputUnitTests.java

Originally, the LCS response parsing depended on the order of the returned map. The `len` field updates when adding the values to the `matches` values. Just a simple fix to verify first which key was read in the `#set(ByteBuffer)` method.

fix: Lcs response parse

---

src/main/java/io/lettuce/core/pubsub/PubSubEndpoint.java
src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
src/test/java/io/lettuce/core/pubsub/PubSubCommandIntegrationTests.java
src/test/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImplUnitTests.java

Resubscribe logic ignoring Pub/Sub shard channels after reconnect. #2940

---

src/main/java/io/lettuce/core/output/BooleanListOutput.java
src/test/java/io/lettuce/core/commands/CommandInterfacesIntegrationTests.java

Implement missing method in the BooleanListOutput
Closes #2612

Command interface - issues with async array results #2612

---

pom.xml
src/main/java/io/lettuce/core/RedisHandshake.java
src/test/java/io/lettuce/core/RedisHandshakeUnitTests.java

Using custom credentials provider can delay providing credentials. In this case **applyPostHandshake** and **applyConnectionMetadata** got executed before **handshake** and led to a NOAUTH error in the log for CLIENT command.
Closes #2996

io.lettuce.core.RedisCommandExecutionException: NOAUTH Authentication required on CLIENT and READONLY command

---

src/main/java/io/lettuce/core/internal/Futures.java
src/test/java/io/lettuce/core/internal/FuturesUnitTests.java

Backport #2943 to the 6.4.x branch
---------

Add defensive copy for Futures allOf() method (#2943)

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisClusterPubSubAsyncCommandsImpl.java
src/test/java/io/lettuce/core/commands/GeoMasterReplicaIntegrationTests.java

only if master & replica configured 
Divert pure read intentions of **georadius** and **georadiusbymember** commands (variants that do not use STORE/STOREDIST) to GEORADIUS_RO/GEORADIUSBYMEMBER_RO This will unify the behavior between Cluster and Redis Standalone/Replica arrangements
Relates to  issues #1481 #2568 #2871
Closes #1813
- [+] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [+] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
- [+] You applied code formatting rules using the `mvn formatter:format` target. Don’t submit any formatting related changes.
- [+] You submit test cases (unit or …

OpsForGeo producing "READONLY You can't write against a read only replica " on READS... 

---

src/main/java/io/lettuce/core/cluster/api/async/RedisClusterAsyncCommands.java
src/main/java/io/lettuce/core/cluster/api/reactive/RedisClusterReactiveCommands.java
src/test/java/io/lettuce/core/RedisContainerIntegrationTests.java
src/test/java/io/lettuce/core/json/RedisJsonClusterIntegrationTests.java
src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java

Closes #3048
Added missing ASYNC and REACTIVE interfaces for the cluster commands
Added tests to verify the change works
Changed the way the testcontainers are being started

Json commands not exposed in AsyncCluster #3048

---

.github/workflows/benchmarks.yml
pom.xml

Fixing benchmark flow

---

src/main/java/io/lettuce/core/RedisHandshake.java
src/test/java/io/lettuce/core/RedisHandshakeUnitTests.java

We now complete the handshake future exceptionally if handshake settings do not match our expectations. This can happen if e.g. the connection id is being sent as String instead of an integer.
See also:
* https://github.com/Prompt-oven/auth-service/issues/16
* https://github.com/microsoft/garnet/issues/811

Propagate handshake failures to Handshake future

---

.github/workflows/integration.yml
.github/workflows/release-drafter.yml

Make sure we execute the step to report test execution to catch failed tests
(additionally) disable ReleaseDrafter as it is not helping, leaving it as manual step

Test failures not reported because step is skipped

---

src/test/java/io/redis/examples/async/HashExample.java

My first attempt at a Lettuce async code example for the [hash datatype page](https://redis.io/docs/latest/develop/data-types/hashes/). Although it passes the CI, I expect it's not ideal in terms of good practice. In particular:
- Is it OK to run the `del()` call at the start from the `CompletableFuture.allOf()` call?
- Where an example snippet depends on the results of the previous snippet, I've taken the variable from the previous snippet and continued from it (eg, `CompletableFuture<Void> hmGet = setGetAll.thenCompose(...` Is this the best way to handle this?
Any other feedback about style, technique, and general Java knowledge would be very welcome :-)

DOC-4528 async hash examples

---

src/main/java/io/lettuce/core/ClientOptions.java
src/main/java/io/lettuce/core/datastructure/queue/HashIndexedQueue.java
src/main/java/io/lettuce/core/protocol/CommandHandler.java
src/test/java/io/lettuce/core/datastructure/queue/HashIndexedQueueTests.java

fix: prevent blocking event loop thread by replacing ArrayDeque with HashIndexedQueue

---

src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java
src/test/java/io/lettuce/core/protocol/DefaultEndpointUnitTests.java

Fix https://github.com/lettuce-io/lettuce-core/issues/2598 
If `write()` comes in between the line `this.channel = channel` and `sharedLock.doExclusive(() -> {}` in `notifyChannelActive()`, the FIFO order is violated since the previous entered commands have not been flushed yet.
See the test case `writeShouldGuaranteeFIFOOrder()`
- [Y] You have read the [contribution guidelines](https://github.com/lettuce-io/lettuce-core/blob/main/.github/CONTRIBUTING.md).
- [N] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request. (No since it is a bug fix instead of a feature).
- [Y] You use the code formatters provided [here](https://github.com/lettuce-io/lettuce-core/blob/main/formatting.xml) …

Fix: make sure FIFO order between write and notify channel active

---

src/main/java/io/lettuce/core/BitFieldArgs.java
src/test/java/io/lettuce/core/commands/BitCommandIntegrationTests.java
src/test/java/io/lettuce/core/commands/reactive/BitReactiveCommandIntegrationTests.java

Some offset field types were long, some were int. I unified them into int type.
Bitfield offset did not support unsigned integer value, so I fixed it.
#2964

Add support up to max unsigned integer in Bitfield offset (#2964)

---

pom.xml
src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/RedisAsyncCommandsImpl.java
src/main/java/io/lettuce/core/RedisReactiveCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisClusterClient.java

Public API methods removed by mistake when introducing RedisJSON #3070

---

.github/workflows/benchmarks.yml
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java

Relates to feature request: [Improve mget method implementation using Java 8 Streams]
This PR refactors the `mget` method in `RedisAdvancedClusterReactiveCommandsImpl.java` to improve code readability and maintainability by utilizing Java 8 Streams and reactive programming patterns.
- Uses manual for loops to build publisher list
- Complex nested iteration structure
- Less readable code for handling partitioned data
- Uses `flatMapIterable` instead of more idiomatic reactive approach
- Replaced manual publisher list creation with Stream API
- Simplified partition handling using functional approach
- Improved reactive chain using `flatMapMany(Flux::fromIterable)`
- Maintained same functionality with cleaner implementation
- Replaced `for` loop with …

refactor mget method improved readability and efficiency

---

src/main/java/io/lettuce/core/protocol/CommandHandler.java
src/main/java/io/lettuce/core/protocol/DecodeBufferPolicies.java
src/test/java/io/lettuce/core/protocol/CommandHandlerUnitTests.java

Improve code by adding some null checks

---

src/main/java/io/lettuce/core/output/KeyValueListOutput.java
src/test/java/io/lettuce/core/commands/HashCommandIntegrationTests.java

UnsupportedOperationException from ListSubscriber during hrandfieldWithvalues #3122

---

pom.xml
src/test/java/io/lettuce/TestTags.java
src/test/java/io/lettuce/authx/EntraIdClusterIntegrationTests.java
src/test/java/io/lettuce/authx/EntraIdIntegrationTests.java
src/test/java/io/lettuce/authx/EntraIdManagedIdentityIntegrationTests.java
src/test/java/io/lettuce/authx/EntraIdTestContext.java
src/test/java/io/lettuce/test/env/Endpoints.java

Prepare EntraId integration tests for inclusion in EntraId nightly tests
Changes introduced with this review:
- Separated EntraID standalone & cluster tests (`EntraIdIntegrationTests.java`, `EntraIdClusterIntegrationTests.java`)
- Added EntraID managed identity integration test - `EntraIdManagedIdentityIntegrationTests.java`
- Read EntraID test env settings from `endpoints.json`
- get rid of `dotenv-java`
- EntraID related tests marked with `entraid` tag
To run entraId-related tests you use:
`mvn  integration-test -Pentraid-it`
Prerequisites: 
- Redis server configured with enabled EntraID authentication
- Provide required info in EntraIdTestContext.

Lettuce EntraID integration tests

---

.github/workflows/integration.yml
src/test/java/io/lettuce/core/ScanIteratorIntegrationTests.java
src/test/java/io/lettuce/core/ScanStreamIntegrationTests.java
src/test/java/io/lettuce/core/cluster/ScanIteratorIntegrationTests.java
src/test/java/io/lettuce/core/commands/HashCommandIntegrationTests.java
src/test/java/io/lettuce/core/commands/StreamCommandIntegrationTests.java
src/test/kotlin/io/lettuce/core/ScanFlowIntegrationTests.kt

Introduce test matrix based on Redis server versions

---

src/test/java/io/lettuce/core/RedisContainerIntegrationTests.java
src/test/resources/docker/docker-compose.yml

In case REDIS_STACK_VERSION is not explicitly set, an empty string is propagated by surefire plugin causing containerised test infra to fail to start

Fix 'make test' test failures

---

src/test/java/io/redis/examples/async/StringExample.java

DOC-4802 fix string example concurrency

---

docs/advanced-usage.md

Fixing a few minor but eye-catching typos.

Fix several typos on the advanced-usage page

---

.github/workflows/stale-issues.yml

Improvements to the close stale issues flow
- bump to latest version
- add more operations per turn

Stale issues action bump

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/ClientOptions.java
src/main/java/io/lettuce/core/RedisAsyncCommandsImpl.java
src/main/java/io/lettuce/core/RedisJsonCommandBuilder.java
src/main/java/io/lettuce/core/RedisReactiveCommandsImpl.java
src/main/java/io/lettuce/core/StatefulRedisConnectionImpl.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
src/main/java/io/lettuce/core/cluster/RedisClusterClient.java
src/main/java/io/lettuce/core/cluster/StatefulRedisClusterConnectionImpl.java
src/main/java/io/lettuce/core/masterreplica/StatefulRedisMasterReplicaConnectionImpl.java
src/main/java/io/lettuce/core/sentinel/RedisSentinelReactiveCommandsImpl.java
src/main/java/io/lettuce/core/sentinel/StatefulRedisSentinelConnectionImpl.java
src/test/java/biz/paluch/redis/extensibility/MyExtendedRedisClusterClient.java
src/test/java/biz/paluch/redis/extensibility/MyRedisClusterConnection.java
src/test/java/io/lettuce/core/ClientOptionsUnitTests.java
src/test/java/io/lettuce/core/RedisJsonCommandBuilderUnitTests.java
src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java

report block error when use with reactor mode #3168 (6.5.x)

---

src/main/java/io/lettuce/core/RedisJsonCommandBuilder.java
src/test/java/io/lettuce/core/RedisJsonCommandBuilderUnitTests.java

Closes #3198 
Several of the JSON.* commands were treating default path in a wrong way

Some json command assume optional path while it's not (#3198)

---

src/main/java/io/lettuce/core/RedisJsonCommandBuilder.java
src/test/java/io/lettuce/core/RedisJsonCommandBuilderUnitTests.java
src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java

json.arrpop forces index=-1 with root path (#3214)

---

src/main/java/io/lettuce/core/protocol/CommandExpiryWriter.java

It is very frustrating to get a stacktrace which does not indicate which command has failed when using async/reactive clients.
I did not create a feature request first, as this is a straightforward change.

Include command type in the timeout message

---

docs/advanced-usage.md

update Limitations section to reflect shaded JAR deprecation #3088 
Closes #3088

docs: update Limitations section to reflect shaded JAR deprecation

---

src/test/java/io/lettuce/authx/DefaultAzureCredentialsIntegrationTests.java
src/test/java/io/lettuce/authx/EntraIdIntegrationTests.java

https://github.com/redis/lettuce/pull/3230 introduced new test 
EntraIdIntegrationTests.azureTokenAuthWithDefaultAzureCred but broke setup for other tests
credentialsProvider might not be initialised and lead to NPE.

Fix NPE in EntraIdIntegrationTests

---

src/main/java/io/lettuce/core/support/ConnectionPoolSupport.java
src/test/java/io/lettuce/core/dynamic/RedisCommandsIntegrationTests.java
src/test/java/io/lettuce/core/support/ConnectionPoolSupportIntegrationTests.java

Overview
---
- Introduce Predicate<T extends StatefulConnection> for connection validation
- Add new overload to ConnectionPoolSupport.createGenericObjectPool()
- Implement ConnectionPoolConfig to encapsulate validation and wrapping options
- Update RedisPooledObjectFactory to use custom validation logic
Closes #3081

Add custom connection validation to ConnectionPoolSupport #3081

---

src/main/java/io/lettuce/core/cluster/NodeSelectionInvocationHandler.java

Replace String.join with Collectors.joining to avoid intermediate collection creation, improving performance by eliminating the unnecessary List creation step.
This optimization changes the `getNodeDescription()` method to use the more efficient Stream collector pattern, which directly collects stream elements into a joined string rather than first collecting to an intermediate list. While the functional outcome remains identical, this approach avoids the unnecessary memory allocation of the temporary list collection, resulting in improved performance especially in high-throughput scenarios.
The existing test suite confirms that the behavior remains consistent with the previous implementation.
Closes #3261

Optimize string concatenation in NodeSelectionInvocationHandler.getNodeDescription()

---

.github/workflows/integration.yml
pom.xml
src/test/java/io/lettuce/core/sentinel/SentinelAclIntegrationTests.java

Revert CI to ubuntu-latest

---

docs/getting-started.md
pom.xml

Bump integration branch to next release (6.7.x)

---

src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java

Improve the performance of obtaining write connections through double-check locks.

---

src/main/java/io/lettuce/core/resource/Transports.java

Change native library default to epoll over io_uring

---

src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java

The purpose of this PR is to adjust the disconnectedBehavior option to prevent timeouts when Redis is shutdown, addressing issue #2866.

Adjusting disconnectedBehavior Option to Prevent Timeout During Redis Shutdown #2866

---

pom.xml
src/test/java/io/lettuce/TestTags.java
src/test/java/io/lettuce/scenario/ConnectionInterruptionReactiveTest.java
src/test/java/io/lettuce/scenario/FaultInjectionClient.java
src/test/java/io/lettuce/scenario/RecommendedSettingsProvider.java
src/test/java/io/lettuce/scenario/ReconnectionEvent.java
src/test/java/io/lettuce/scenario/ReconnectionStats.java
src/test/java/io/lettuce/scenario/ReconnectionTimingTracker.java
src/test/resources/log4j2-test.xml

- Use reactor-netty-http client to interact with the Fault Injector
- Test command execution and PubSub with dmc_restart, network_failure failures injected

Add basic connection interruption tests

---

src/main/java/io/lettuce/core/RedisURI.java
src/test/java/io/lettuce/core/ClientOptionsIntegrationTests.java
src/test/java/io/lettuce/core/RedisURIBuilderUnitTests.java
src/test/java/io/lettuce/core/RedisURIUnitTests.java
src/test/java/io/lettuce/core/cluster/RedisClusterURIUtilUnitTests.java
src/test/java/io/lettuce/core/masterreplica/StaticMasterReplicaIntegrationTests.java
src/test/java/io/lettuce/core/masterslave/StaticMasterSlaveIntegrationTests.java
src/test/java/io/lettuce/core/sentinel/SentinelAclIntegrationTests.java
src/test/java/io/lettuce/core/sentinel/SentinelConnectionIntegrationTests.java

This PR removes the deprecated `withPassword(String)` method from `RedisURI.Builder` as discussed in #3328.
Existing code that calls `withPassword(String)` will continue to work without modification because:
- String implements CharSequence
- All existing string parameters will automatically route to `withPassword(CharSequence)` method
- The functionality remains identical
This approach minimizes the breaking change impact while still removing the deprecated method. All existing tests continue to pass without modification.
This PR is a follow-up to #1157 and addresses part of #3328.

chore: deprecated withPassword(String) method (#3328)

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/CommandListenerWriter.java
src/main/java/io/lettuce/core/RedisChannelHandler.java
src/main/java/io/lettuce/core/RedisChannelWriter.java
src/main/java/io/lettuce/core/api/StatefulConnection.java
src/main/java/io/lettuce/core/api/async/BaseRedisAsyncCommands.java
src/main/java/io/lettuce/core/api/reactive/BaseRedisReactiveCommands.java
src/main/java/io/lettuce/core/api/sync/BaseRedisCommands.java
src/main/java/io/lettuce/core/cluster/ClusterConnectionProvider.java
src/main/java/io/lettuce/core/cluster/ClusterDistributionChannelWriter.java
src/main/java/io/lettuce/core/cluster/PooledClusterConnectionProvider.java
src/main/java/io/lettuce/core/masterreplica/MasterReplicaChannelWriter.java
src/main/java/io/lettuce/core/masterreplica/MasterReplicaConnectionProvider.java
src/main/java/io/lettuce/core/masterslave/MasterSlaveConnectionWrapper.java
src/main/java/io/lettuce/core/protocol/CommandExpiryWriter.java
src/main/java/io/lettuce/core/protocol/ConnectionFacade.java
src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java
src/main/templates/io/lettuce/core/api/BaseRedisCommands.java
src/test/java/io/lettuce/core/ClientIntegrationTests.java
src/test/java/io/lettuce/core/cluster/ClusterCommandIntegrationTests.java
src/test/java/io/lettuce/core/cluster/RedisClusterClientIntegrationTests.java

This PR completes the removal of the unsafe `reset()` method from Lettuce, finalizing deprecations from versions 5.2 and 6.2. The change addresses [#3328](https://github.com/redis/lettuce/issues/3328) and [#907](https://github.com/redis/lettuce/issues/907).
* Eliminated the `reset()` method from the API and implementation.
* Removed related documentation and deprecation markers.
* **Breaking Change**: Code referencing `reset()` will fail to compile.

Remove deprecated `reset()` method from Lettuce API and internals

---

src/main/java/io/lettuce/core/MaintenanceEventsOptions.java
src/main/java/io/lettuce/core/RedisHandshake.java
src/main/java/io/lettuce/core/protocol/MaintenanceAwareConnectionWatchdog.java
src/test/java/io/lettuce/core/protocol/MaintenanceAwareConnectionWatchdogUnitTests.java

This change extends Lettuce’s support for Redis **maintenance event notifications** by adding the none option for `moving-endpoint-type` when enabling maintenance events.
According to the specification, `moving-endpoint-type` determines whether the `MOVING` push message contains an internal/external IP or FQDN.
The new special value none indicates that the `MOVING` message should not contain any endpoint; instead, the endpoint field is null.
When the client receives a MOVING message with moving-endpoint-type=none, it will schedule a **graceful reconnect** to the currently configured endpoint after half of the grace period specified in the message has elapsed.
- 	Added support for moving-endpoint-type=none option in CLIENT MAINT_NOTIFICATIONS.
- 	Implemented delayed rebind behavior: …

[hitless upgrade] Support for none moving-endpoint-type in maintenance event notifications (CAE-1285)

---

.github/wordlist.txt
RELEASE-NOTES.md
pom.xml

Release Lettuce 6.8.1.RELEASE

---

src/main/java/io/lettuce/core/AbstractRedisClient.java
src/main/java/io/lettuce/core/ClientOptions.java
src/main/java/io/lettuce/core/ConnectionBuilder.java
src/main/java/io/lettuce/core/MaintNotificationsConfig.java
src/main/java/io/lettuce/core/RedisHandshake.java
src/main/java/io/lettuce/core/TimeoutOptions.java
src/main/java/io/lettuce/core/protocol/CommandExpiryWriter.java
src/main/java/io/lettuce/core/protocol/CommandHandler.java
src/main/java/io/lettuce/core/protocol/MaintenanceAwareComponent.java
src/main/java/io/lettuce/core/protocol/MaintenanceAwareConnectionWatchdog.java
src/main/java/io/lettuce/core/protocol/MaintenanceAwareExpiryWriter.java
src/main/java/io/lettuce/core/protocol/RebindState.java
src/test/java/io/lettuce/core/MaintNotificationsConfigUnitTests.java
src/test/java/io/lettuce/core/RedisHandshakeUnitTests.java
src/test/java/io/lettuce/core/tracing/BraveTracingIntegrationTests.java
src/test/java/io/lettuce/scenario/RelaxedTimeoutConfigurationTest.java

Renames configuration classes and properties for better clarity and consistency in maintenance notification handling.
**Consistent Naming**: Aligns with Redis maintenance notifications terminology
- Renamed main configuration class from `MaintenanceEventsOptions` to `MaintNotificationsConfig`
- Updated method names:
- `supportMaintenanceEvents()` → `enableMaintNotifications()`
- `supportsMaintenanceEvents()` → `maintNotificationsEnabled()`
- `getMaintenanceEventsOptions()` → `getMaintNotificationsConfig()`
- Updated builder method: `supportMaintenanceEvents()` → `maintNotificationsConfig()`
- Renamed enum `AddressType` to `EndpointType` for better semantic clarity
- Renamed related classes and methods:
- `AddressTypeSource` → `EndpointTypeSource`
- `getAddressType()` → `getEndpointType()` …

[hitless upgrade] Rename maintenance notification configuration properties

---

src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
src/main/java/io/lettuce/core/RediSearchCommandBuilder.java
src/main/java/io/lettuce/core/api/async/RediSearchAsyncCommands.java
src/main/java/io/lettuce/core/api/reactive/RediSearchReactiveCommands.java
src/main/java/io/lettuce/core/api/sync/RediSearchCommands.java
src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionSearchAsyncCommands.java
src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionSearchCommands.java
src/main/java/io/lettuce/core/search/arguments/AggregateArgs.java
src/main/java/io/lettuce/core/search/arguments/CreateArgs.java
src/main/java/io/lettuce/core/search/arguments/FieldArgs.java
src/main/kotlin/io/lettuce/core/api/coroutines/RediSearchCoroutinesCommands.kt
src/main/kotlin/io/lettuce/core/api/coroutines/RediSearchCoroutinesCommandsImpl.kt
src/main/templates/io/lettuce/core/api/RediSearchCommands.java
src/test/java/io/lettuce/core/search/RediSearchVectorIntegrationTests.java

As part of #3455 
List of commands changed:
``` java
FT.SEARCH (ftSearch)
FT.AGGREGATE (ftAggregate)
FT.TAGVALS (ftTagvals) -
FT.SPELLCHECK (ftSpellcheck)
FT.DICTDUMP (ftDictdump)
FT.EXPLAIN (ftExplain)
FT.SYNDUMP (ftSyndump)
FT.CURSOR READ (ftCursorread)
FT.CURSOR DEL (ftCursordel)
FT.CREATE (ftCreate)
FT.ALIASADD (ftAliasadd)
FT.ALIASUPDATE (ftAliasupdate)
FT.ALIASDEL (ftAliasdel)
FT.ALTER (ftAlter)
FT.DROPINDEX (ftDropindex)
FT.DICTADD (ftDictadd)
FT.DICTDEL (ftDictdel)
FT.SYNUPDATE (ftSynupdate)
```

Make search commands truly keyless
