- src/main/java/com/lambdaworks/redis/pubsub/RedisPubSubConnectionImpl.java
Listeners might be added after subscription and a disconnection can happen in between the two
Listeners may also be added and removed dynamically causing subscriptions to be lost on reconnection
> Resubscribe even when there are no listeners

- src/main/java/com/lambdaworks/redis/cluster/ClusterTopologyRefresh.java
- src/main/java/com/lambdaworks/redis/cluster/models/partitions/Partitions.java
- src/test/java/com/lambdaworks/redis/cluster/ClusterTopologyRefreshTest.java
I did this against master, which is 3.4. Should I rebase this on 4.0?
> Don't add nodes that have noaddr flag set.

- src/main/java/com/lambdaworks/redis/resource/DefaultClientResources.java
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/mp911de/lettuce/205)
> Fix comparison for computationThreadPoolSize

- src/main/java/io/lettuce/core/api/reactive/RedisStringReactiveCommands.java
Hello! 
Small one, I think it was a typo :)
> Typo in string reactive commands

- src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
- src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
- src/main/java/io/lettuce/core/RedisCommandBuilder.java
- src/main/java/io/lettuce/core/api/async/RedisSortedSetAsyncCommands.java
- src/main/java/io/lettuce/core/api/reactive/RedisSortedSetReactiveCommands.java
- src/main/java/io/lettuce/core/api/sync/RedisSortedSetCommands.java
- src/main/java/io/lettuce/core/cluster/api/async/NodeSelectionSortedSetAsyncCommands.java
- src/main/java/io/lettuce/core/cluster/api/sync/NodeSelectionSortedSetCommands.java
- src/main/kotlin/io/lettuce/core/api/coroutines/RedisSortedSetCoroutinesCommands.kt
- src/main/kotlin/io/lettuce/core/api/coroutines/RedisSortedSetCoroutinesCommandsImpl.kt
- src/main/templates/io/lettuce/core/api/RedisSortedSetCommands.java
- src/test/java/io/lettuce/core/commands/SortedSetCommandIntegrationTests.java
closes [https://github.com/lettuce-io/lettuce-core/issues/1663](https://github.com/lettuce-io/lettuce-core/issues/1663)
> Rename zrandmemberWithscores to zrandmemberWithScores

- src/main/java/io/lettuce/core/FlushMode.java
> Fix comment in FlushMode

- src/main/java/io/lettuce/core/KillArgs.java
- src/test/java/io/lettuce/core/commands/ServerCommandIntegrationTests.java
Resolves [https://github.com/lettuce-io/lettuce-core/issues/1672](https://github.com/lettuce-io/lettuce-core/issues/1672)
> Add support CLIENT KILL USER

- pom.xml
Proposed fix for https://github.com/lettuce-io/lettuce-core/issues/1949
> Upgrade to Netty 4.1.72.Final

- README.md
> Fix Javadoc link in README

- src/main/java/io/lettuce/core/cluster/ClusterTopologyRefreshOptions.java
Fix a little typo in project
- [] You have created a feature request first to discuss your contribution intent. Please reference the feature request ticket number in the pull request.
> Fix a little typo

- pom.xml
> ISSUE-2098 Bump Netty to 4.1.77

- src/main/java/io/lettuce/core/ReadFrom.java
Ignoring above check list since this only fixes a minor documentation issue.
> Fixes typo in ReadFrom

- src/main/java/io/lettuce/core/RedisURI.java
- src/test/java/io/lettuce/core/RedisURIUnitTests.java
Proposed fix for:
https://github.com/lettuce-io/lettuce-core/issues/2328
> Apply `SslVerifyMode` in `RedisURI. applySsl(…)`

- pom.xml
The current version is vulnerable to CVE-2023-34462
> Upgrade to Netty 4.1.94.Final

- .github/workflows/cicd.yaml
> bump setup-java to v4

- .github/workflows/codeql.yaml
> Created CodeQL analysis configuration by modifying suggested template

- src/test/java/io/lettuce/core/RedisClientIntegrationTests.java
... so I've changed the check to also wait some time before failing to accommodate the slower builders
> Flaky integration test frequently fails the pipeline

- src/main/java/io/lettuce/core/resource/DefaultClientResources.java
> Mark dnsResolver(DnsResolver) as deprecated.

- .github/workflows/version-and-release.yaml
Updated release acton (as part of #2880)
* Modify the release action to call the proper maven target for release
* Make releasing manually available too
> Updated release acton (as part of #2880)

- .github/workflows/version-and-release.yaml
- pom.xml
(as part of #2880)
- modified a few of the steps in the release process workflow
- modified the release notes to reflect the contents in the 6.4.0 release
- modified the Maven pom.xml to include the step to upload the artifacts to Sonatype Nexus and also sign the keys in a specific way
> Fixed the release flow (6.4.x branch)

- README.md
Minor updates to the README
- [] You submit test cases (unit or integration tests) that back your changes.
> Add badges to the README.md file

- src/main/java/io/lettuce/core/pubsub/RedisPubSubReactiveCommandsImpl.java
fixing https://github.com/redis/lettuce/issues/2971
> fix(2971): spublish typo fix

- src/main/java/io/lettuce/core/pubsub/RedisPubSubReactiveCommandsImpl.java
Crossport to the 6.4.x branch
closes #2971
> (crossport to 6.4.x) spublish typo fix (#2972)

- src/main/java/io/lettuce/core/pubsub/PubSubEndpoint.java
- src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
- src/test/java/io/lettuce/core/pubsub/PubSubCommandTest.java
- src/test/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImplUnitTests.java
…ection and re-connection.
Backport to 6.4.x branch
> Sharded PubSub subscriptions not recovered after disconn… #2940 

- .github/workflows/integration.yml
> Restore missing step

- src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
> Run reactive MGET in parallel #2395

- .github/workflows/version-and-release.yaml
> Adding the release flow to the 6.1.x branch

- src/main/java/io/lettuce/core/protocol/SharedLock.java
- src/test/java/io/lettuce/core/protocol/SharedLockTest.java
Backport #2961 to the 6.4.x branch
> fix:deadlock when reentrant exclusive lock #2905 #2879 (#2961)

- RELEASE-NOTES.md
- pom.xml
> Missing configuration for release

- .github/workflows/benchmarks.yml
- pom.xml
- src/test/jmh/io/lettuce/core/JmhMain.java
> Workflow for running benchmarks weekly

- .github/workflows/benchmarks.yml
> Using the right name for the file this time

- src/main/java/io/lettuce/core/StatefulRedisConnectionImpl.java
- src/main/java/io/lettuce/core/cluster/StatefulRedisClusterConnectionImpl.java
- src/main/java/io/lettuce/core/masterreplica/StatefulRedisMasterReplicaConnectionImpl.java
- src/main/java/io/lettuce/core/pubsub/StatefulRedisPubSubConnectionImpl.java
- src/main/java/io/lettuce/core/sentinel/StatefulRedisSentinelConnectionImpl.java
Closes #3054 
Restoring the constructors that were present before the changes introduced in #2933 
> Restore API that was accidently deleted when introducing the JSON feature

- RELEASE-NOTES.md
- pom.xml
> Set next minor release for integration branch

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Releasing 6.4.2

- src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
- src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
- src/main/java/io/lettuce/core/RedisAsyncCommandsImpl.java
- src/main/java/io/lettuce/core/RedisReactiveCommandsImpl.java
- src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java
- src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
- src/main/java/io/lettuce/core/cluster/RedisClusterClient.java
Crossport for the integration branch of the changes in #3070
> Public API methods removed by mistake when introducing RedisJSON #3070

- src/main/java/io/lettuce/core/protocol/CommandArgs.java
- src/test/java/io/lettuce/core/AuthenticationIntegrationTests.java
- src/test/java/io/lettuce/core/RedisCommandBuilderUnitTests.java
- src/test/java/io/lettuce/core/commands/AclCommandIntegrationTests.java
> Handle UTF-8 characters in command arguments #3071

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Release Lettuce 6.5.2.RELEASE #3111

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
As part of https://github.com/redis/lettuce/issues/3139
> Releasing Lettuce 6.5.3 #3139

- .github/workflows/docs.yml
> Bump to v4 of checkout

- .github/workflows/docs.yml
> Update publish docs action to use latest versions of actions

- src/main/java/io/lettuce/core/AbstractRedisAsyncCommands.java
- src/main/java/io/lettuce/core/AbstractRedisReactiveCommands.java
- src/main/java/io/lettuce/core/ClientOptions.java
- src/main/java/io/lettuce/core/RedisAsyncCommandsImpl.java
- src/main/java/io/lettuce/core/RedisJsonCommandBuilder.java
- src/main/java/io/lettuce/core/RedisReactiveCommandsImpl.java
- src/main/java/io/lettuce/core/StatefulRedisConnectionImpl.java
- src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterAsyncCommandsImpl.java
- src/main/java/io/lettuce/core/cluster/RedisAdvancedClusterReactiveCommandsImpl.java
- src/main/java/io/lettuce/core/cluster/RedisClusterClient.java
- src/main/java/io/lettuce/core/cluster/StatefulRedisClusterConnectionImpl.java
- src/main/java/io/lettuce/core/masterreplica/StatefulRedisMasterReplicaConnectionImpl.java
- src/main/java/io/lettuce/core/sentinel/RedisSentinelReactiveCommandsImpl.java
- src/main/java/io/lettuce/core/sentinel/StatefulRedisSentinelConnectionImpl.java
- src/test/java/biz/paluch/redis/extensibility/MyExtendedRedisClusterClient.java
- src/test/java/biz/paluch/redis/extensibility/MyRedisClusterConnection.java
- src/test/java/io/lettuce/core/ClientOptionsUnitTests.java
- src/test/java/io/lettuce/core/RedisJsonCommandBuilderUnitTests.java
- src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java
> report block error when use with reactor mode #3168

- src/test/resources/docker/docker-compose.yml
> Bump default client-libs-test container version

- pom.xml
> Bump netty.version to 4.1.118.Final #3187

- docs/user-guide/connecting-redis.md
> Fix typo & add withSsl() in  connecting to Entra ID enabled Redis doc

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Release Lettuce 6.5.4.RELEASE #3190

- src/main/java/io/lettuce/core/json/DefaultJsonParser.java
- src/main/java/io/lettuce/core/json/UnproccessedJsonValue.java
- src/main/java/io/lettuce/core/output/JsonValueListOutput.java
- src/test/java/io/lettuce/core/json/RedisJsonIntegrationTests.java
> Exception on zpopmin (#3196) (6.5.x)

- src/main/java/io/lettuce/core/output/ReplayOutput.java
- src/test/java/io/lettuce/core/pubsub/PubSubCommandIntegrationTests.java
The command relaying logic was missing a handler for double output.
Closes #3199 
> Exeption on zpopmin (#3199)

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Release Lettuce 6.5.5.RELEASE (#3209)

- src/main/java/io/lettuce/core/cluster/ClusterTopologyRefreshOptions.java
not empty means , it must contain at least one element
> Updates enableAdaptiveRefreshTrigger trigger assertion message

- .github/wordlist.txt
- docs/advanced-usage.md
- src/main/java/io/lettuce/core/ClientOptions.java
- src/main/java/io/lettuce/core/protocol/DefaultEndpoint.java
- src/test/java/io/lettuce/core/cluster/ClusterNodeEndpointUnitTests.java
- src/test/java/io/lettuce/core/reliability/AtLeastOnceIntegrationTests.java
> Introduce command replay filter to avoid command replaying after reconnect #1310

- .github/wordlist.txt
- RELEASE-NOTES.md
> Releasing Lettuce 6.6.0.BETA4

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Releasing Lettuce 6.6.0.RELEASE 

- src/test/java/io/redis/examples/async/SortedSetExample.java
[DOC-4756](https://redislabs.atlassian.net/browse/DOC-4756)
PR redone to include latest CI updates and to use `join()` to guarantee running order of `CompletableFuture` objects.
[DOC-4756]: https://redislabs.atlassian.net/browse/DOC-4756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4756 sorted set examples with join()

- src/test/java/io/redis/examples/async/ListExample.java
[DOC-4757](https://redislabs.atlassian.net/browse/DOC-4757)
Note: the example for `rule_1.1` uses `handle()` to deal with the intentional exception caused by using `lpush` on a string key. Is this the best way to do it? 
[DOC-4757]: https://redislabs.atlassian.net/browse/DOC-4757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DOC-4757 list examples using join()

- .github/workflows/integration.yml
Recent runs sporadically fail with integration tests not being able to reach the test containers.
When we inspect the build we see :
```go
970d5e68fb7b Extracting [==================================================>]     793B/793B
970d5e68fb7b Extracting [==================================================>]     793B/793B
970d5e68fb7b Pull complete 
970d5e68fb7b Pull complete 
clustered-stack Pulled 
standalone-stack Pulled 
fatal error: concurrent map writes
fatal error: concurrent map writes
goroutine 73 [running]:
github.com/docker/compose/v2/pkg/compose.(*composeService).pullRequiredImages.func1.1()
github.com/docker/compose/v2/pkg/compose/pull.go:328 +0x236
golang.org/x/sync/errgroup.(*Group).Go.func1()
golang.org/x/sync@v0.13.0/errgroup/errgroup.go:79 +0x50
created by …
```
> CI to pull containers in a serial way

- src/main/java/io/lettuce/core/resource/Transports.java
> NoClassDefFoundError in Lettuce 6.7.0 #3317

- .github/wordlist.txt
- RELEASE-NOTES.md
- pom.xml
> Release Lettuce 6.7.1.RELEASE #3320

- .github/workflows/snapshot.yaml
- .github/workflows/version-and-release.yaml
- pom.xml
Test run https://github.com/redis/lettuce/actions/runs/16124095007
> Migrate publishing to Maven Central Portal

- src/test/java/io/lettuce/core/ClientOptionsUnitTests.java
- src/test/java/io/lettuce/core/protocol/MaintenanceAwareConnectionWatchdogUnitTests.java
- src/test/java/io/lettuce/core/protocol/MaintenanceAwareExpiryWriterUnitTests.java
- src/test/java/io/lettuce/test/ReflectionTestUtils.java
> [Hitless upgrades] Add unit tests for the newly introduced classes #3355

- src/main/java/io/lettuce/core/json/DefaultJsonParser.java
- src/main/java/io/lettuce/core/json/DelegateJsonObject.java
- src/main/java/io/lettuce/core/json/DelegateJsonValue.java
- src/test/java/io/lettuce/core/json/DelegateJsonObjectUnitTests.java
> Fix a NullPointerException in DelegateJsonObject #3417

- .github/wordlist.txt
- RELEASE-NOTES.md
> Release 7.0.0.BETA1 (#3437)

- src/test/jmh/io/lettuce/core/protocol/EmptyClientResources.java
After introducing breaking changes for the 7.x release we accidentally broke the compilation of the benchmarks branch
> Fixing compilation error in benchmark code

- RELEASE-NOTES.md
> Release Lettuce 7.0.0.BETA2

- .github/workflows/docs.yml
- requirements.txt
GH workflows - docs action - bump python version and pin dependency versions
> GH workflows - fix docs action
